#! /bin/bash
set -euo pipefail

python3 --version
python3 -m venv .venv
source .venv/bin/activate

python3 -m pip install --upgrade pip --requirement requirements.dev.txt
python3 -m pytest . -v && python3 -m mypy .
