name: Format and MDSnippets and Lint Fix
on:
  push:
  workflow_dispatch:
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Format and Lint Fix
      run: |
        ./format_code.sh
    - name: Update MarkdownSnippets
      run: |
        dotnet tool install --global MarkdownSnippets.Tool
        mdsnippets ${GITHUB_WORKSPACE}
    - name: Git Commit and Push
      uses: github-actions-x/commit@v2.9
      with:
        github-token: "${secrets.GITHUB_TOKEN}"
        commit-message: ". d ruff formatting and linting"
        rebase: 'true'
        push-branch: 'main'
        name: github actions
        email: actions@github.com 
