# Tests for ensure_uv_installed, which are difficult to write as unit tests because they depend on machine state that will be modified be the tests start

name: Test ensure_uv_installed

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test__ensure_uv_installed:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./test__ensure_uv_installed
